### ISSUE TITLE
GpuService sample doesn't work!

### ISSUE THREAD

**Issue by quinvit** [gigya/microdot-samples#4]
Hi, I pull this repository and try to run GpuService. The first time I got error could not find loadPaths.json. I added that file and after started GpuService host, then I run the Client. Here is what I got https://i.gyazo.com/1858a105b368c77a3821770e189ba57c.png at GpuService host console. This is from Client console https://i.gyazo.com/478d548e3a64deed9f670ce697d32194.png

**Comment by quinvit** [comment]
Finally I try to update latest nuget packages, using .net 4.7 , config Discovery.config and it works fine now. Can I push to another branch or create a pull request?

**Comment by tsibelman** [comment]
Sure, PR are welcomed.

**Comment by Allon-Guralnek** [comment]
Fixed by @quinvit via PR #5. Thanks!
